name: SimpleSky
version: '${project.version}'
main: com.chillguy.simplerealm.Main
api-version: '1.20'
commands:
  simplereload:
  unclaim:
  claim:
  realm:
  home:
  visit:
  configrealm:
  border:
depends: [SimpleInventory,WorldEdit,Vault, LuckPerms]
softdepend: [PlaceholderAPI]