name: SimpleSky
version: '1.0-SNAPSHOT'
main: com.venned.simplerealm.Main
api-version: '1.20'
commands:
  simplereload:
  unclaim:
  claim:
  realm:
  home:
  visit:
  configrealm:
  border:
depends: [SimpleInventory,WorldEdit,Vault, LuckPerms]
softdepend: [PlaceholderAPI]